# Guest OS timezone
timezone: UTC
# Are we need check box updates for every 'vagrant up'?
box_check_update: false
# Virtual machine name
machine_name: eth
# Virtual machine IP
ip: 192.168.66.66
# Virtual machine CPU cores number
cpus: 1
# Virtual machine RAM
memory: 2048

# Ethereum Proof-of-Authority
# Domains

dashboard: eth.devel
faucet: faucet.eth.devel
wallet: wallet.eth.devel
stats: stats.eth.devel
