#!/usr/bin/expect -f

set ip [lindex $argv 1];
set domain [lindex $argv 8];
set network_name [lindex $argv 9];
set genesis_file [lindex $argv 10];
set secret_api_password [lindex $argv 11];
set location [lindex $argv 12];

set timeout -1

# Create puppeth .puppeth
spawn puppeth
expect "Please specify a network name"
send "$network_name\n"
expect "2. Configure new genesis"
send "2\n"
expect "2. Import already existing genesis"
send "2\n"
expect "Where's the genesis file?"
send "$genesis_file\n"
expect "3. Track new remote server"
send "3\n"
expect "What is the remote server's address"
send "$ip\n"
expect "The authenticity of host"
send "yes\n"

# Deploy network components
expect "4. Deploy network components"
send "4\n"
expect "1. Ethstats  - Network monitoring tool"
send "1\n"
expect "1. $ip"
send "1\n"
expect "Which port should ethstats listen on? (default = 80)"
send "\n"
expect "Allow sharing the port with other services"
send "\n"
expect "Proxy deployed, which domain to assign?"
send "stats.$domain\n"
expect "What should be the secret password for the API?"
send "$secret_api_password\n"

# Deploy bootnode
expect "4. Manage network components"
send "4\n"
expect "3. Deploy new network component"
send "3\n"
expect "2. Bootnode  - Entry point of the network"
send "2\n"
expect "1. $ip"
send "1\n"
expect "Where should data be stored on the remote machine?"
send "$location/bootnode\n"
expect "Which TCP/UDP port to listen on? (default = 30303)"
send "\n"
expect "How many peers to allow connecting?"
send "\n"
expect "How many light peers to allow connecting?"
send "\n"
expect "What should the node be called on the stats page?"
send "bootnode\n"

# Deploy wallet
expect "4. Manage network components"
send "4\n"
expect "4. Deploy new network component"
send "4\n"
expect "5. Wallet"
send "5\n"
expect "1. $ip"
send "1\n"
expect "Which port should the wallet listen on? "
send "\n"
expect "Shared port, which domain to assign? "
send "wallet.$domain\n"
expect "Where should data be stored on the remote machine?"
send "$location/wallet\n"
expect "Which TCP/UDP port should the backing node listen on? (default = 30303)"
send "30310\n"
expect "Which port should the backing RPC API listen on? (default = 8545)"
send "8546\n"
expect "What should the wallet be called on the stats page?"
send "wallet\n"

# Deploy faucet
expect "4. Manage network components"
send "4\n"
expect "5. Deploy new network component"
send "5\n"
expect "6. Faucet    - Crypto faucet to give away funds"
send "6\n"
expect "1. $ip"
send "1\n"
expect "Which port should the faucet listen on? (default = 80)"
send "\n"
expect "Shared port, which domain to assign? "
send "faucet.$domain\n"
expect "How many Ethers to release per request? "
send "10\n"
expect "How many minutes to enforce between requests? "
send "3\n"
expect "How many funding tiers to feature "
send "3\n"
expect "Enable reCaptcha protection against robots (y/n)? "
send "\n"
expect "Where should data be stored on the remote machine?"
send "$location/faucet\n"
expect "Which TCP/UDP port should the light client listen on? (default = 30303)"
send "30311\n"
expect "What should the node be called on the stats page?"
send "faucet\n"
expect "Please paste the faucet's funding account key JSON:"
set output [exec cat /app/vagrant/config/accounts/alloc--3e216b18e24c6cbe4c68e68b8c7bfebd664526c4]
send "$output\n"
expect "What's the unlock password for the account? (won't be echoed)"
send "testpasswd\n"
expect "Permit non-authenticated funding requests (y/n)? (default = false)"
send "y\n"

# Deploy dashboard
expect "4. Manage network components"
send "4\n"
expect "6. Deploy new network component"
send "6\n"
expect "7. Dashboard - Website listing above web-services"
send "7\n"
expect "1. $ip"
send "1\n"
expect "Which port should the dashboard listen on? (default = 80)"
send "\n"
expect "Shared port, which domain to assign? "
send "$domain\n"
expect "Which ethstats service to list? "
send "\n"
expect "Which explorer service to list? "
send "\n"
expect "Which wallet service to list? "
send "\n"
expect "Which faucet service to list? "
send "\n"
expect "Include ethstats secret on dashboard (y/n)?"
send "\n"

expect "What would you like to do? (default = stats)"

exit
